# Logistic Regression

In [2]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
os.getcwd()

os.chdir('C:\\Users\\iZfig\OneDrive\Desktop\Mini_project\DataSet')

df=pd.read_csv('df_clean.csv')
df.head()

Year  Month  Day  Rain  Evap  MaxTemp  MinTemp  WindVelocity  \
0  2018      1    1   0.0   3.3     29.8     10.4           2.4   
1  2018      1    2   0.0   4.0     29.6     11.4           2.1   
2  2018      1    3   0.0   3.6     29.2     13.4           3.2   
3  2018      1    4   0.0   3.5     28.6     10.8           3.4   
4  2018      1    5   0.0   4.6     28.2      9.6           4.4   

   Solar_Radiation  Bright_Sunshine  Rel_Humidity  PM2.5  
0             16.2              9.3            89  56.22  
1             15.8              9.0            89  63.57  
2             12.7              8.4            88  72.61  
3             13.9              6.0            89  68.25  
4             14.1              7.3            88  70.88

In [3]:
df.head()

Year  Month  Day  Rain  Evap  MaxTemp  MinTemp  WindVelocity  \
0  2018      1    1   0.0   3.3     29.8     10.4           2.4   
1  2018      1    2   0.0   4.0     29.6     11.4           2.1   
2  2018      1    3   0.0   3.6     29.2     13.4           3.2   
3  2018      1    4   0.0   3.5     28.6     10.8           3.4   
4  2018      1    5   0.0   4.6     28.2      9.6           4.4   

   Solar_Radiation  Bright_Sunshine  Rel_Humidity  PM2.5  
0             16.2              9.3            89  56.22  
1             15.8              9.0            89  63.57  
2             12.7              8.4            88  72.61  
3             13.9              6.0            89  68.25  
4             14.1              7.3            88  70.88

# NO Null Values 

# Data Transformation
For Logistic Regression Target has to be a Categorical Value.

In [4]:
df['target_cd'] = pd.cut(df['PM2.5'],bins=[0,50,500], labels=[0,1])
df['target_cd']

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     0
      ..
555    0
556    0
557    0
558    0
559    0
560    0
561    0
562    0
563    0
564    0
565    0
566    0
567    0
568    0
569    0
570    0
571    0
572    0
573    0
574    0
575    0
576    0
577    0
578    0
579    0
580    0
581    0
582    0
583    0
584    0
Name: target_cd, Length: 585, dtype: category
Categories (2, int64): [0 < 1]

In [5]:
df.head()

Year  Month  Day  Rain  Evap  MaxTemp  MinTemp  WindVelocity  \
0  2018      1    1   0.0   3.3     29.8     10.4           2.4   
1  2018      1    2   0.0   4.0     29.6     11.4           2.1   
2  2018      1    3   0.0   3.6     29.2     13.4           3.2   
3  2018      1    4   0.0   3.5     28.6     10.8           3.4   
4  2018      1    5   0.0   4.6     28.2      9.6           4.4   

   Solar_Radiation  Bright_Sunshine  Rel_Humidity  PM2.5 target_cd  
0             16.2              9.3            89  56.22         1  
1             15.8              9.0            89  63.57         1  
2             12.7              8.4            88  72.61         1  
3             13.9              6.0            89  68.25         1  
4             14.1              7.3            88  70.88         1

In [6]:
df["target_cd"].value_counts()


0    418
1    167
Name: target_cd, dtype: int64

In [7]:
X = df[["Year", "Month","Rain","MinTemp","WindVelocity"]]
y = df["target_cd"]

# Train Test Split

In [8]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.4, random_state=1)

In [9]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 351 entries, 395 to 37
Data columns (total 5 columns):
Year            351 non-null int64
Month           351 non-null int64
Rain            351 non-null float64
MinTemp         351 non-null float64
WindVelocity    351 non-null float64
dtypes: float64(3), int64(2)
memory usage: 16.5 KB


In [10]:
y_train

395    1
577    0
293    1
245    0
115    0
335    1
404    0
533    0
494    0
315    1
139    0
106    0
82     1
204    0
244    0
221    0
246    0
379    0
88     0
185    0
323    1
419    1
528    0
249    0
122    0
164    0
579    0
239    0
392    0
498    0
      ..
209    0
316    0
513    0
313    1
534    0
319    0
7      1
393    1
141    0
86     0
478    0
503    0
215    0
562    0
398    0
490    0
252    0
468    0
357    1
254    0
276    1
178    0
281    1
390    1
508    0
129    0
144    0
72     0
235    0
37     0
Name: target_cd, Length: 351, dtype: category
Categories (2, int64): [0 < 1]

In [11]:
features = X_train.iloc[:,:].values
features

array([[2.019e+03, 2.000e+00, 0.000e+00, 1.840e+01, 9.400e+00],
       [2.019e+03, 8.000e+00, 6.000e-01, 2.280e+01, 6.200e+00],
       [2.018e+03, 1.000e+01, 6.000e-01, 2.220e+01, 3.700e+00],
       ...,
       [2.018e+03, 3.000e+00, 4.000e-01, 1.880e+01, 7.100e+00],
       [2.018e+03, 8.000e+00, 4.500e+00, 2.220e+01, 9.600e+00],
       [2.018e+03, 2.000e+00, 0.000e+00, 1.360e+01, 4.200e+00]])

In [12]:
labels = y_train.iloc[:].values
labels

[1, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0]
Length: 351
Categories (2, int64): [0 < 1]

In [13]:
X=features
y=labels

# Instantiate Logistic Regression model
After Feature Selection,we instantiate LogisticRegression model and fit the Features and target to the Model

In [14]:
from sklearn.linear_model.logistic import LogisticRegression
lgsr=LogisticRegression(random_state=0)
lgsr.fit(X,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
y_predictions=lgsr.predict(X_test)
y_predictions

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [16]:
#Check model accuracy
from sklearn.metrics import confusion_matrix
conf_matrix=confusion_matrix(y_predictions,y_test)
conf_matrix

array([[156,  17],
       [ 13,  48]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score
acc_sco=accuracy_score(y_test,y_predictions)
acc_sco

0.8717948717948718

In [18]:
#Evaluating the model 
from sklearn.metrics import mean_squared_error, r2_score

# printing values
print('Slope:' ,lgsr.coef_)
print('Intercept:', lgsr.intercept_)
print("\n")

Slope: [[ 0.00426369  0.09548695 -0.07554334 -0.3931655  -0.40691431]]
Intercept: [-2.91973388e-05]




 # IPY Widget for Prediction using Logistic Regression model

In [26]:
import ipywidgets as widgets
from ipywidgets import interact, interact_manual

from IPython.display import display
t1=widgets.FloatText(
    value=7.5,
    description='Year:',
    disabled=False
)
t2=widgets.FloatText(
    value=7.5,
    description='Month:',
    disabled=False
)
t3=widgets.FloatText(
    value=7.5,
    description='Rainfall in mm:',
    disabled=False
)
t4=widgets.FloatText(
    value=7.5,
    description='Temp in C:',
    disabled=False
)
t5=widgets.FloatText(
    value=7.5,
    description='Wind Velocity in kmph:',
    disabled=False
)


display(t1,t2,t3,t4,t5)


FloatText(value=7.5, description='Year:')

FloatText(value=7.5, description='Month:')

FloatText(value=7.5, description='Rainfall in mm:')

FloatText(value=7.5, description='Temp in C:')

FloatText(value=7.5, description='Wind Velocity in kmph:')

In [27]:
out = widgets.Output(layout={'border': '5px solid green'})
pred= lgsr.predict([[(t1.value),(t2.value),(t3.value),(t4.value),(t5.value)]])
with out:
    if pred==1:
        print("PM2.5 Concentration is high")
    else:
        print("PM2.5 Concentration is low")
display(t1,t2,t3,t4,t5,out)

FloatText(value=7.5, description='Year:')

FloatText(value=7.5, description='Month:')

FloatText(value=7.5, description='Rainfall in mm:')

FloatText(value=7.5, description='Temp in C:')

FloatText(value=7.5, description='Wind Velocity in kmph:')

Output(layout=Layout(border='5px solid green'))